### ISSUE TITLE
Something about AnyGenerator in the book

### ISSUE THREAD

**Issue by lancy** [objcio/advanced-swift#1]
In the chapter Collection: Generators and Value Semantics:

It's written that AnyGenerator does not have value semantics, it captured the passing g1 by reference, so any calls to next on either g1 or g3 increment the same underlying generator instance.

But when I run the code in the Xcode, it give out a different results from the book, which seems like Swift 2.2 already changed this behaviour: g1 and g3 work separately, it take a copy when create an AnyGenerator.

May this help.

``` swift
let seq = 0.stride(through: 9, by: 1)
var g1 = seq.generate()
g1.next() // 0
g1.next() // 1
g1.next() // 2

var g2 = g1
g1.next()  // 3
g2.next()  // 3
g2.next()  // 4

var g3 = AnyGenerator(g1)

g3.next() // 4
g1.next() // 4
g3.next() // 5
g1.next() // 5
```

**Comment by lancy** [comment]
Eh, I found something interesting:

``` swift
let seq = 0.stride(through: 9, by: 1)
var g1 = seq.generate()
g1.next() // 0
g1.next() // 1
g1.next() // 2

var g2 = g1
g1.next()  // 3
g2.next()  // 3
g2.next()  // 4

// It will copy g1, besides "let" is ok.
let g3 = AnyGenerator(g1)

g3.next() // 4
g1.next() // 4
g3.next() // 5
g1.next() // 5

// Even though AnyGenerator is a struct, this will not make a copy...
let g4 = g3

g4.next() // 6
g3.next() // 7
g4.next() // 8
g3.next() // 9
g1.next() // 6
```

**Comment by ole** [comment]
Yes, you are right. This behavior changed when `AnyGenerator` (now `AnyIterator` in Swift 3) was turned from a class to a struct, and we missed updating the example. This will be fixed in the upcoming update for Swift 3. Good catch, thanks!
