### ISSUE TITLE
Code formatting issue in iBooks 

### ISSUE THREAD

**Issue by jcavar** [objcio/advanced-swift#7]
<img width="1190" alt="screen shot 2018-01-03 at 13 25 34" src="https://user-images.githubusercontent.com/3751289/34520620-b2b7c1ac-f089-11e7-9f4d-1025b0dd90b3.png">

**Comment by jcavar** [comment]
There are couple more of these. You can search in iBooks for ``` and see them easily.

**Comment by ole** [comment]
@jcavar Thanks! Yes, the EPUB version did indeed have some formatting errors. Sorry!

We fixed these and posted a new version to Gumroad a few weeks ago. You should be able to download it from Gumroad ("Advanced-Swift-Dec-2017"). I can't find any more of these errors in the new version.

I'm gonna close this, but feel free to reopen it if you find other issues.
